name: Backport

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport pull request
    steps:
    - uses: syndesisio/backport-action@v1
